ALTER TABLE public.appointments
  ADD COLUMN IF NOT EXISTS sala TEXT,
  ADD COLUMN IF NOT EXISTS parcelas_total INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS parcelas_pagas INTEGER NOT NULL DEFAULT 0;